In [ ]:
#Зинёв Владимир ПМ21-6

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep

In [10]:
def parse_it(url):
  results = dict()
  results['title'] = []
  results['mean_rating'] = []

  for i in range(10):
      url_use = url + f'?page={i}'
      r = requests.get(url_use)
      sleep(3)
      soup = BeautifulSoup(r.text, 'lxml')
      
      elements = soup.find('div', class_ = 'view-content')
      titles = [i.text for i in elements.findAll('div', class_ = 'title')]
      all_rating = [i for i in elements.findAll('div', class_ = 'rating')]
      mean_rating = [i.findAll('span', class_ = 'average-rating')[0].text.replace('Среднее: ','') for i in all_rating]
      
      results['title'].extend(titles)
      results['mean_rating'].extend(mean_rating)
  return pd.DataFrame(results, index = range(1,201))

#Фильмы

In [14]:
url = 'https://irecommend.ru/catalog/list/47'
films = parse_it(url)

In [15]:
films

                                                 title mean_rating
1                              Чебурашка (2022, фильм)        4.4
2               Обитель зла: Раккун-Сити (2021, фильм)          3
3    Следующие 365 дней / The next 365 days / Kolej...        2.3
4                          Дети кукурузы (2020, фильм)          3
5     Неприкасаемые / Intouchables (1+1) (2011, фильм)        4.9
..                                                 ...         ...
196            Лицо со шрамом / Scarface (1983, фильм)        4.6
197                              Веном 2 (2021, фильм)        3.7
198                        Ледяной драйв (2021, фильм)        4.2
199            Тихая гавань / Safe Haven (2013, фильм)        4.3
200                           Ликвидация (2007, фильм)          5

[200 rows x 2 columns]

##сохраняем полученную таблицу в ксв файл

In [20]:
films.to_csv (r'film_reviews.csv', index= False )

#Книги

In [22]:
url = 'https://irecommend.ru/catalog/list/7'
books = parse_it(url)

In [23]:
books

                                                 title mean_rating
1    Как быстро и легко выучить иностранный язык за...          5
2    Гарри Поттер и философский камень / Harry Pott...        4.8
3    Ленивая гениальная мама. Как отделить важное о...          5
4                Под стеклянным колпаком. Сильвия Плат        4.1
5    Система минус 60 или Мое волшебное похудение, ...        4.7
..                                                 ...         ...
196                        Мятежница. Оксана Гринберга          5
197              Попалась, птичка! Милена Завойчинская          5
198  Общаться с ребенком. Как? , Юлия Борисовна Гип...        4.7
199  О-ПА-ПОПА! Качаем попку дома и в зале. Елена С...        4.5
200                         Приворот. Марьяна Романова        4.3

[200 rows x 2 columns]

##сохраняем полученную таблицу в ксв файл

In [24]:
books.to_csv (r'books_reviews.csv', index= False )

#Бытовая техника

In [25]:
url = 'https://irecommend.ru/catalog/list/3'
techniques = parse_it(url)

In [26]:
techniques

                                                 title mean_rating
1    Кухонная машина Kenwood Cooking Chef XL KCL95....          5
2            Роликовый массажер для лица Olzori E-wave          4
3               Аппарат для чистки лица ReadySkin Nova          5
4                     Выпрямитель волос Centek CT-2017          5
5                     Эпилятор  Лазерный Tria Laser 4X          5
..                                                 ...         ...
196   Пистолет для прокалывания ушей Studex Система-75        4.5
197                              Миксер Gorenje M450WS          5
198                      Дверной видеоглазок Eques S31          5
199                     Весы кухонные KITFORT KT-803-6        4.9
200              Приложение Bewitching: маджонг тайлы!          5

[200 rows x 2 columns]

##сохраняем полученную таблицу в ксв файл

In [27]:
techniques.to_csv (r'techniques_reviews.csv', index= False )